[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマー
repo = 'mrkn/mrkn256.vim'

[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]] # インデントの可視化
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # git情報
repo ='tpope/vim-fugitive'

[[plugins]] # ステータスライン系
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightLineFugitive',
      \   'readonly': 'LightLineReadonly',
      \   'modified': 'LightLineModified',
      \   'filename': 'LightLineFilename'
      \ },
      \ 'separator': { 'left': ' >>', 'right': '<' },
      \ 'subseparator': { 'left': ' >>', 'right': '<' }
      \ }

'''

[[plugins]] # git操作
repo = 'lambdalisue/vim-gita'
on_cmd = 'Gita'

[[plugins]] # ファイラー
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'
